package com.example.clase3listadoadapters;

public final class ListOfCars {
    public static String[] getListOfCars(){
        return new String[]{
                "Mercedes Benz",
                "Toyota",
                "BMW",
                "FIAT",
                "CHEVROLET",
                "FERRARI",
                "Mercedes Benz",
                "Toyota",
                "BMW",
                "FIAT",
                "CHEVROLET",
                "FERRARI",
                "Mercedes Benz",
                "Toyota",
                "BMW",
                "FIAT",
                "CHEVROLET",
                "FERRARI",
                "Mercedes Benz",
                "Toyota",
                "BMW",
                "FIAT",
                "CHEVROLET",
                "FERRARI",
                "Mercedes Benz",
                "Toyota",
                "BMW",
                "FIAT",
                "CHEVROLET",
                "FERRARI",
                "Mercedes Benz",
                "Toyota",
                "BMW",
                "FIAT",
                "CHEVROLET",
                "FERRARI",
                "Mercedes Benz",
                "Toyota",
                "BMW",
                "FIAT",
                "CHEVROLET",
                "FERRARI",
        };
    }
}
